language: generic

sudo: false

matrix:
    include:
        - env: PROJECT=projects/projectA
        - env: PROJECT=projects/projectB

script:
    - echo "Commit range $TRAVIS_COMMIT_RANGE"
    - if git diff --name-only $TRAVIS_COMMIT_RANGE | sort -u | uniq | grep $PROJECT > /dev/null; then echo "$PROJECT is being built"; else "$PROJECT is NOT being built"; fi
